### ISSUE TITLE
enable cross installation of packages from github that require compilation

### ISSUE THREAD

**Issue by jeffeaton** [dide-tools/context#13]
Feature request: It would be great to integrate with the buildr package to enable cross installation of packages sourced from github that require compilation.

ctx <- context::context_save(...,
                                                packages="<package>",
                                                package_sources=context::package_sources(github="<user>/<package>"),
                                                 ...)

**Comment by richfitz** [comment]
This is implemented now in https://github.com/dide-tools/didewin/commit/bcd9454cbcd79bd304434254739a35a07cb65c5c - can you give it a shot?

**Comment by jeffeaton** [comment]
Works like a treat!! Thanks!
