### ISSUE TITLE
Delete cached downloads

### ISSUE THREAD

**Issue by jackolney** [dide-tools/context#15]
Is it possible to delete the cache? I *accidentally* attempted to install a package that was not a package... no DESCRIPTION, but I can't figure out how to delete the cache to download the fix.

**Comment by richfitz** [comment]
No support for doing this from the package at present; just go into `<context_root>/R/x86_64-w64-mingw32` and delete packages as required

**Comment by jackolney** [comment]
Thanks, Rich – figured this might be the thing to do. Will give it a go!

**Comment by richfitz** [comment]
Moved to https://github.com/richfitz/provisionr/issues/3
